name: Deploy to EC2 (Dockerfile)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to EC2 using Dockerfile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Ensure known_hosts has EC2 host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -T 60 -H ${{ secrets.EC2_HOST }} 2>/dev/null >> ~/.ssh/known_hosts || \
          (echo "Failed to resolve EC2_HOST: ${{ secrets.EC2_HOST }}" && exit 1)

      - name: Debug SSH key and user
        run: |
          echo "Using SSH user: ${{ secrets.EC2_USER }}"
          echo "Checking if private key is loaded..."
          ssh-add -l

      - name: Test SSH connection (verbose)
        run: |
          ssh -vvv -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo 'SSH connection successful'" || \
          (echo "SSH connection failed. Check that EC2_SSH_KEY matches the EC2_USER and is added to the instance's authorized_keys." && exit 1)

      - name: Sync files to EC2 (rsync)
        run: |
          REMOTE_PATH="/home/${{ secrets.EC2_USER }}/app"
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" --exclude='.git' ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${REMOTE_PATH}

      - name: Build and run Docker container on EC2 from Dockerfile
        run: |
          REMOTE_PATH="/home/${{ secrets.EC2_USER }}/app"
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "\
            cd ${REMOTE_PATH} && \
            docker build -t my-app . && \
            docker stop my-app || true && \
            docker rm my-app || true && \
            docker run -d --name my-app -p 80:8089 my-app"

      - name: Notify success
        run: echo "Dockerfile build and deployment finished"

# NOTES:
# - Added verbose SSH output for easier troubleshooting.
# - Added a debug step to confirm SSH key is loaded and matches EC2_USER.
# - If SSH still fails, verify that the EC2 instance's authorized_keys contains the public key for EC2_SSH_KEY and that the security group allows SSH from GitHub Actions runners.
